updated

diff --git a/.github/workflows/e2e.yml b/.github/workflows/e2e.yml
--- a/.github/workflows/e2e.yml
+++ b/.github/workflows/e2e.yml
@@ -175,7 +175,7 @@ jobs:
           mkdir -p "${HOME}/.gardener"
           export GARDENER_KUBECONFIG="${HOME}/.gardener/kubeconfig"
           echo ${GARDENER_KYMATUNAS} | base64 --decode > ${GARDENER_KUBECONFIG}
-          : # generate cluster name and export it to Github env for other steps to access it.
+          : # generate cluster name and export it to Github env for cleanup step to access it.
           export CLUSTER_NAME="${CLUSTER_PREFIX}$(openssl rand -hex 2)"
           echo "CLUSTER_NAME=${CLUSTER_NAME}" >> $GITHUB_ENV
           : # provision gardener cluster.
@@ -185,6 +185,107 @@ jobs:
           kubectl get nodes
           kubectl get ns
 
+      - name: Create kyma-system namespace
+        run: |
+          kubectl create ns kyma-system || true
+
+      - name: Create EventMesh secret
+        env:
+          EVENTMESH_K8S_SECRET: ${{ secrets.EVENTMESH_K8S_SECRET }}
+        run: |
+          echo ${EVENTMESH_K8S_SECRET} | base64 --decode > kubectl apply -n kyma-system -f -
+
+      - name: Create IAS application for EventMesh
+        env:
+          TEST_EVENTING_AUTH_IAS_URL: ${{ vars.EVENTING_AUTH_IAS_URL }}
+          TEST_EVENTING_AUTH_IAS_USER: ${{ vars.EVENTING_AUTH_IAS_USER }}
+          TEST_EVENTING_AUTH_IAS_PASSWORD: ${{ secrets.EVENTING_AUTH_IAS_PASSWORD }}
+        run: |
+          export DISPLAY_NAME=${CLUSTER_NAME}
+          make -C hack/ci/ create-ias-app
+
+      - name: Install latest released Istio Module
+        run: |
+          make -C hack/ci/ install-istio-module
+
+      - name: Install latest released API Gateway Manager
+        run: |
+          make -C hack/ci/ install-api-gateway-module
+
+      - name: Install latest released NATS Manager
+        run: |
+          make -C hack/ci/ install-nats-module
+
+      - name: Deploy eventing-manager
+        run: |
+          make install
+          make deploy IMG=$MANAGER_IMAGE
+          kubectl apply -f config/samples/default.yaml
+
+      - name: Wait for Installed modules to be ready
+        run: |
+          make -C hack/ci/ wait-istio-cr-ready
+          make -C hack/ci/ wait-api-gateway-cr-ready
+          make -C hack/ci/ wait-nats-cr-ready
+          make -C hack/ci/ wait-eventing-cr-ready-with-backend ACTIVE_BACKEND=NATS
+
+      - name: Setup eventing tests
+        run: |
+          make e2e-eventing-setup
+
+      - name: Test eventing with NATS
+        run: |
+          make e2e-eventing
+
+      - name: Switch to EventMesh backend
+        run: |
+          kubectl apply -f config/samples/default_eventmesh.yaml
+          make -C hack/ci/ wait-eventing-cr-ready-with-backend ACTIVE_BACKEND=EventMesh         
+
+      - name: Test eventing with EventMesh
+        env:
+          BACKEND_TYPE: "EventMesh"
+        run: |
+          : # wait for subscriptions to be ready.
+          make e2e-eventing-setup
+          : # run tests.
+          make e2e-eventing
+
+      - name: Switch back to NATS backend
+        run: |
+          kubectl apply -f config/samples/default.yaml
+          make -C hack/ci/ wait-eventing-cr-ready-with-backend ACTIVE_BACKEND=NATS
+
+      # Run make e2e-eventing again with NATS backend
+      - name: Test eventing again with NATS
+        run: |
+          : # wait for subscriptions to be ready.
+          make e2e-eventing-setup
+          : # run tests.
+          make e2e-eventing
+
+      - name: Test eventing cleanup
+        run: |
+          make e2e-cleanup
+
+      - name: On error, fetch module CRs
+        if: failure()
+        run: |
+          kubectl get nats.operator.kyma-project.io -n kyma-system -o yaml
+          kubectl get eventing.operator.kyma-project.io -n kyma-system -o yaml
+          kubectl get istios.operator.kyma-project.io -n kyma-system -o yaml
+          kubectl get apigateways.operator.kyma-project.io -n kyma-system -o yaml
+
+      - name: Delete IAS application
+        if: ${{ always() }}
+        env:
+          TEST_EVENTING_AUTH_IAS_URL: ${{ vars.EVENTING_AUTH_IAS_URL }}
+          TEST_EVENTING_AUTH_IAS_USER: ${{ vars.EVENTING_AUTH_IAS_USER }}
+          TEST_EVENTING_AUTH_IAS_PASSWORD: ${{ secrets.EVENTING_AUTH_IAS_PASSWORD }}
+        run: |
+          export IAS_APPLICATION_LOCATION=$(cat ~/.ias_location)
+          make -C hack/ci/ delete-ias-app
+
       - name: Delete Gardener cluster
         if: ${{ always() }}
         env:
@@ -193,4 +294,4 @@ jobs:
           WAIT_FOR_DELETE_COMPLETION: "false"
         run: |
           export GARDENER_KUBECONFIG="${HOME}/.gardener/kubeconfig"
-#          make -C hack/ci/ deprovision-gardener-cluster
+          make -C hack/ci/ deprovision-gardener-cluster
